name: 02 - Workflow Events
on:
  - push
  - workflow_dispatch
  - schedule:
    - cron: '0 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo $GITHUB_EVENT_NAME