name: 07 - Using Expressions
run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}
# run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug || false }}

on:
  # push:
  workflow_dispatch:
    inputs:
      debug:
        required: true
        type: boolean
        default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.debug
        name: '[debug] Print start-up data'
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name}}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - if: inputs.debug && github.ref_name == 'main'
        name: '[debug] Print when triggered from main'
        run: echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world!"